# Google Cloud Run Deployment Configuration for Project Pravaah ADK Agents
# Urban Mobility Operating System - Multi-Agent ADK Deployment

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pravaah-adk-agents
  namespace: default
  labels:
    app: pravaah
    version: adk-v1
    environment: production
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      labels:
        app: pravaah
        version: adk-v1
      annotations:
        # GCP optimizations
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "1"
        run.googleapis.com/timeout: "900"
        
        # ADK specific configurations
        run.googleapis.com/vpc-access-connector: "pravaah-vpc-connector"
        run.googleapis.com/vpc-access-egress: "all-traffic"
        
        # Monitoring and logging
        run.googleapis.com/enable-audit-logs: "true"
        run.googleapis.com/enable-execution-environment-logs: "true"
    spec:
      serviceAccountName: pravaah-agent-runner@stable-sign-454210-i0.iam.gserviceaccount.com
      containerConcurrency: 100
      timeoutSeconds: 900
      containers:
      - name: pravaah-adk-agents
        image: gcr.io/stable-sign-454210-i0/pravaah-adk-agents:latest
        ports:
        - name: http1
          containerPort: 8080
          protocol: TCP
        env:
        # Google Cloud Configuration
        - name: GOOGLE_CLOUD_PROJECT
          value: "stable-sign-454210-i0"
        - name: GOOGLE_CLOUD_REGION
          value: "asia-south1"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/app/serviceAccountKey.json"
        
        # ADK Configuration
        - name: ADK_CONFIG_PATH
          value: "/app/adk_config.yaml"
        - name: ADK_AGENT_REGISTRY_COLLECTION
          value: "agent_registry"
        - name: ADK_MESSAGING_TOPIC
          value: "pravaah-a2a-messages"
        
        # Firestore Configuration
        - name: FIRESTORE_PROJECT_ID
          value: "stable-sign-454210-i0"
        - name: FIRESTORE_DATABASE
          value: "(default)"
        
        # Pub/Sub Configuration
        - name: PUBSUB_PROJECT_ID
          value: "stable-sign-454210-i0"
        - name: PUBSUB_TOPIC_PREFIX
          value: "pravaah"
        
        # Vertex AI Configuration
        - name: VERTEX_AI_PROJECT_ID
          value: "stable-sign-454210-i0"
        - name: VERTEX_AI_LOCATION
          value: "asia-south1"
        - name: VERTEX_AI_MODEL
          value: "gemini-1.5-pro"
        
        # Agent Configuration
        - name: AGENT_ENVIRONMENT
          value: "production"
        - name: AGENT_LOG_LEVEL
          value: "INFO"
        - name: AGENT_HEALTH_CHECK_INTERVAL
          value: "60"
        - name: AGENT_METRICS_ENABLED
          value: "true"
        
        # Performance Configuration
        - name: ASYNCIO_WORKERS
          value: "4"
        - name: MAX_CONCURRENT_REQUESTS
          value: "100"
        - name: REQUEST_TIMEOUT
          value: "300"
        
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        # Startup probe for ADK initialization
        startupProbe:
          httpGet:
            path: /startup
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30

---
# Cloud Run Service for Individual Agents (if needed for scaling)

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pravaah-observer-agent
  labels:
    app: pravaah
    agent: observer
    version: adk-v1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "500m"
        run.googleapis.com/max-scale: "5"
        run.googleapis.com/min-scale: "1"
    spec:
      serviceAccountName: pravaah-agent-runner@stable-sign-454210-i0.iam.gserviceaccount.com
      containers:
      - name: observer-agent
        image: gcr.io/stable-sign-454210-i0/pravaah-observer-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AGENT_TYPE
          value: "observer"
        - name: GOOGLE_CLOUD_PROJECT
          value: "stable-sign-454210-i0"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pravaah-simulation-agent
  labels:
    app: pravaah
    agent: simulation
    version: adk-v1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "1.5Gi"
        run.googleapis.com/cpu: "750m"
        run.googleapis.com/max-scale: "3"
        run.googleapis.com/min-scale: "1"
    spec:
      serviceAccountName: pravaah-agent-runner@stable-sign-454210-i0.iam.gserviceaccount.com
      containers:
      - name: simulation-agent
        image: gcr.io/stable-sign-454210-i0/pravaah-simulation-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AGENT_TYPE
          value: "simulation"
        - name: GOOGLE_CLOUD_PROJECT
          value: "stable-sign-454210-i0"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pravaah-orchestrator-agent
  labels:
    app: pravaah
    agent: orchestrator
    version: adk-v1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1000m"
        run.googleapis.com/max-scale: "2"
        run.googleapis.com/min-scale: "1"
    spec:
      serviceAccountName: pravaah-agent-runner@stable-sign-454210-i0.iam.gserviceaccount.com
      containers:
      - name: orchestrator-agent
        image: gcr.io/stable-sign-454210-i0/pravaah-orchestrator-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AGENT_TYPE
          value: "orchestrator"
        - name: GOOGLE_CLOUD_PROJECT
          value: "stable-sign-454210-i0"
        - name: VERTEX_AI_LOCATION
          value: "asia-south1"

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pravaah-communications-agent
  labels:
    app: pravaah
    agent: communications
    version: adk-v1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "500m"
        run.googleapis.com/max-scale: "5"
        run.googleapis.com/min-scale: "1"
    spec:
      serviceAccountName: pravaah-agent-runner@stable-sign-454210-i0.iam.gserviceaccount.com
      containers:
      - name: communications-agent
        image: gcr.io/stable-sign-454210-i0/pravaah-communications-agent:latest
        ports:
        - containerPort: 8080
        env:
        - name: AGENT_TYPE
          value: "communications"
        - name: GOOGLE_CLOUD_PROJECT
          value: "stable-sign-454210-i0"
